# Creating gloss vector from nltk corpus (brown)

Experiment to check out on smaller scale

In [1]:
import numpy as np
import scipy
from scipy.sparse import bsr_matrix
import nltk.corpus
from nltk.tokenize import RegexpTokenizer
import re
import matplotlib.pyplot as plt

In [2]:
# Position surrounding word
num_pos = 4
keyword = "serve"

In [3]:
word_list = nltk.corpus.brown.words()
filtered_words = [word for word in word_list if word not in nltk.corpus.stopwords.words('english')]

KeyboardInterrupt: 

In [ ]:
print(len(filtered_words))

In [ ]:
indices = [i for i, x in enumerate(filtered_words) if x == keyword]
print(len(indices))

In [ ]:
tokenizer = RegexpTokenizer(r'\w+')
just_words = tokenizer.tokenize(" ".join(word_list))
just_words = [x.lower() for x in just_words]
unique_words = list(set(just_words))
print(unique_words)

In [ ]:
print(len(unique_words))

In [ ]:
filtered_words_cp = filtered_words.copy()
print(filtered_words_cp[360:370])
print(filtered_words_cp[43340:43350])
index = filtered_words_cp.index(keyword)
print(index)
filtered_words_cp.pop(index)
index = filtered_words_cp.index(keyword)
print(index)

In [ ]:
gloss_vector = np.zeros(len(unique_words))

In [ ]:
indices = [i for i, x in enumerate(filtered_words) if x == keyword]
words_around = []
for i in indices:
    words_around.extend(filtered_words[i - num_pos : i])
    words_around.extend(filtered_words[i + 1 : i + num_pos + 1])

print(words_around)

In [ ]:
for word in words_around:
    if word in unique_words:
        index = unique_words.index(word)
        gloss_vector[index] += 1
        
print(gloss_vector)

In [ ]:
indices = [i for i, x in enumerate(gloss_vector) if x > 0]
for i in indices:
    print(unique_words[i], ": ", gloss_vector[i])

In [ ]:
print(gloss_vector[unique_words.index("tennis")])
print(gloss_vector[unique_words.index("purpose")])
print(gloss_vector[unique_words.index("bird")])
print(gloss_vector[unique_words.index("dinner")])
print(gloss_vector[unique_words.index("lunch")])
print(gloss_vector[unique_words.index("breakfast")])
print(gloss_vector[unique_words.index("food")])
print(gloss_vector[unique_words.index("waiter")])
print(gloss_vector[unique_words.index("restaurant")])

In [ ]:
from nltk.corpus import wordnet as wn
c = 0
for ss in wn.all_synsets():
    # ss = wn.synset("dog")
    print(ss)
    #print(ss.attributes())
    #print(ss.also_sees())
    print(ss.causes())
    #print(ss.closure())
    #print(ss.common_hypernyms())
    print(ss.definition())
    print(ss.entailments())
    print(ss.examples())
    print(ss.frame_ids())
    print(ss.hypernym_distances())
    print(ss.hypernym_paths())
    print(ss.hypernyms())
    print(ss.hyponyms())
    print(ss.instance_hypernyms())
    print(ss.instance_hyponyms())
    #print(ss.jcn_similarity())
    #print(ss.lch_similarity())
    print(ss.lemma_names())
    print(ss.lemmas())
    print(ss.lexname())
    #print(ss.lin_similarity())
    #print(ss.lowest_common_hypernyms())
    print(ss.max_depth())
    print(ss.member_holonyms())
    print(ss.member_meronyms())
    print(ss.min_depth())
    print(ss.name())
    print(ss.offset())
    print(ss.part_holonyms())
    print(ss.part_meronyms())
    #print(ss.path_similarity())
    print(ss.pos())
    print(ss.region_domains())
    #print(ss.res_similarity())
    print(ss.root_hypernyms())
    #print(ss.shortest_path_distance())
    print(ss.similar_tos())
    print(ss.substance_holonyms())
    print(ss.substance_meronyms())
    print(ss.topic_domains())
    #print(ss.tree())
    print(ss.unicode_repr())
    print(ss.usage_domains())
    print(ss.verb_groups())
    #print(ss.wup_similarity())
    print("*****************************************************")
    c += 1
    if c > 9:
        break

In [ ]:
c = 0
for ss in wn.all_synsets():
    c += 1
    
print(c)
num_synsets = c

In [ ]:
c = 0
for w in wn.words():
    c += 1

print(c)

# Main implemantation starts here

In [25]:
from nltk.corpus import wordnet as wn

# Creating corpus
wn_corpus = ""
covered = []
for ss in wn.all_synsets():
    w = ss.name().split(".")[0]
    if w not in covered:
        syns = wn.synsets(w)
        for s in syns:
            wn_corpus += s.definition() + ". " + ". ".join(s.examples()) + ". "
        
        covered.append(w)

In [26]:
len(covered)

86555

In [27]:
print(wn_corpus[0:100])
print(len(wn_corpus))

(usually followed by `to') having the necessary means or skill or know-how or authority to do someth
12504224


In [28]:
# Corpus to array
wn_words = re.sub("[^\w]", " ",  wn_corpus).split()

In [29]:
print(wn_words[1:10])
print(len(wn_words))

['followed', 'by', 'to', 'having', 'the', 'necessary', 'means', 'or', 'skill']
2043791


In [30]:
# Removing Stopwords
wn_filtered_words = [word for word in wn_words if word not in nltk.corpus.stopwords.words('english')]

In [31]:
print(wn_filtered_words[1:10])
print(len(wn_filtered_words))

['followed', 'necessary', 'means', 'skill', 'know', 'authority', 'something', 'able', 'swim']
1215318


In [32]:
# Removing low frequency words
wn_dict = {}
for w in wn_filtered_words:
    word = w.lower()
    if word not in wn_dict.keys():
        wn_dict[word] = 0
    
    wn_dict[word] += 1

In [33]:
len(wn_dict.keys())

55343

In [34]:
wn_dict["usually"]

3012

In [ ]:
# Plotting word frequencies
plt.bar(range(len(wn_dict)), list(wn_dict.values()), align='center')
plt.xticks(range(len(wn_dict)), list(wn_dict.keys()))
plt.show()

In [36]:
wn_dict_copy = wn_dict.copy()

In [37]:
# Number of words for which frequency is less than num are chucked out
# [Selected 4 since it give the size that matches with paper]
num = 4
c = 0
for w, n in wn_dict_copy.items():
    if n < num:
        del wn_dict[w]
        c += 1

print(c)
print(len(wn_dict.keys()))

29441
25902


In [38]:
wn_unique_words = list(wn_dict.keys())

In [39]:
len(wn_unique_words)

25902

In [40]:
wn_gloss_matrix = bsr_matrix((len(wn_unique_words), len(wn_unique_words)), dtype=np.int8).toarray()
r = 0
for w in wn_unique_words:
    wn_words_around = []
    indices = [i for i, x in enumerate(wn_filtered_words) if x == w]
    for i in indices:
        wn_words_around.extend(wn_filtered_words[i - num_pos : i])
        wn_words_around.extend(wn_filtered_words[i + 1 : i + num_pos + 1])
    
    for word in wn_words_around:
        if word in wn_unique_words:
            index = wn_unique_words.index(word)
            wn_gloss_matrix[r][index] += 1
    
    r += 1

In [ ]:
print(wn.synsets("dog"))
for s in wn.synsets("dog"):
    print(s.definition())

In [41]:
np.save('gloss_matrix.v01.npz', wn_gloss_matrix)

In [42]:
print(wn_gloss_matrix[0])
print(wn_gloss_matrix[1])
print(wn_gloss_matrix[2])
print(wn_gloss_matrix[3])
print(wn_gloss_matrix[4])
print(wn_gloss_matrix[5])
print(wn_gloss_matrix[6])
print(wn_gloss_matrix[7])
print(wn_gloss_matrix[8])
print(wn_gloss_matrix[9])
print(wn_gloss_matrix[10])
print(wn_gloss_matrix[11])
print(wn_gloss_matrix[12])
print(wn_gloss_matrix[13])
print(wn_gloss_matrix[14])
print(wn_gloss_matrix[15])
print(wn_gloss_matrix[16])
print(wn_gloss_matrix[17])
print(wn_gloss_matrix[18])
print(wn_gloss_matrix[19])

[42 49  8 ...  0  0  0]
[48 12  3 ...  0  0  0]
[7 2 4 ... 0 0 0]
[14  1  9 ...  0  0  2]
[2 2 2 ... 0 0 0]
[17  2  2 ...  0  0  0]
[5 0 3 ... 0 0 0]
[106   8  18 ...   0   0   0]
[1 1 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[7 1 0 ... 0 0 0]
[5 0 2 ... 0 0 0]
[3 0 0 ... 0 0 0]
[3 0 0 ... 0 0 0]
[11  0  0 ...  0  0  0]
[17  0  2 ...  0  0  0]
[0 1 0 ... 0 0 0]
[2 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [43]:
print(wn_gloss_matrix[0][0:200])

[  42   49    8   15    2   17    5  106    1    0    7    5    3    3
   11   17    0    2    0    0   11   14    1    8    0   27   24    4
    7    0    0    6    5    9    5   13    9    0   10   83    7    0
   10    5   14    0   49    0    6    5   29   39    8    3    4   35
    6    2    5    0    5    0    2   10    1    1   11    0    0    5
   33    0   18    1    2   14    1    7    3   31    8    3   13    2
    0    9    2    3    2   16 -107    6   17    1    0    7    3   39
    4    1    0    1   45    0   15    2    5    0    0    0   13    0
    4    0   16    0    2    0    2    0    2    0   19   15    1    6
    1   11    4    5    0    7    0   33    3   11    1    1   11    0
    1    9    3    0    2    1    0    0    1    4    0    0    4    0
    1    0    0    0    0    7    0    0   11   16    3    2    7    0
    0   20    8    3    0    4    0    0   14    1    2    0    1    0
    4    2    5    1    6    0    7    1    0    0   22    8    1    1
    1 

In [44]:
serve = wn_gloss_matrix[wn_unique_words.index("serve")]
food = wn_gloss_matrix[wn_unique_words.index("food")]
tennis = wn_gloss_matrix[wn_unique_words.index("tennis")]
spoon = wn_gloss_matrix[wn_unique_words.index("spoon")]
player = wn_gloss_matrix[wn_unique_words.index("player")]


In [45]:
in_serve = np.where(np.array(serve) > 0)
in_food = np.where(np.array(food) > 0)
in_tennis = np.where(np.array(tennis) > 0)

In [46]:
in_int_serve_food = np.intersect1d(in_serve, in_food)
in_int_tennis_food = np.intersect1d(in_tennis, in_food)

In [47]:
a1 = []
for i in in_int_serve_food:
    a1.append(wn_unique_words[i])

a2 = []
for i in in_int_tennis_food:
    a2.append(wn_unique_words[i])
    
print(a1)
print(a2)

['usually', 'means', 'something', 'able', 'computer', 'well', 'children', 'young', 'capacity', 'two', 'body', 'man', 'served', 'army', 'without', 'power', 'like', 'hot', 'away', 'surface', 'upper', 'small', 'eye', 'action', 'open', 'relating', 'time', 'death', 'old', 'may', 'little', 'almost', 'way', 'accident', 'wine', 'anger', 'religious', 'person', 'act', 'unit', 'parts', 'event', 'device', 'foot', 'period', 'bad', 'water', 'food', 'several', 'immediately', 'one', 'game', 'place', 'freedom', 'got', 'hospital', 'made', 'put', 'meat', 'animal', 'music', 'first', 'title', 'someone', 'tennis', 'opening', 'gave', 'class', 'make', 'back', 'turn', 'left', 'right', 'group', 'form', 'certain', 'could', 'often', 'another', 'medium', 'create', 'data', 'disk', 'carry', 'function', 'cause', 'diet', 'male', 'animals', 'blood', 'hand', 'machine', 'sold', 'plants', 'play', 'relation', 'control', 'limited', 'expressing', 'direct', 'guide', 'take', 'chief', 'us', 'equipment', 'trained', 'women', 'cou

In [48]:
import math
math.acos(np.dot(serve, food)/(np.linalg.norm(serve)* np.linalg.norm(food))) * 180/math.pi

89.7971720236239

In [49]:
math.acos(np.dot(serve, tennis)/(np.linalg.norm(serve)* np.linalg.norm(tennis))) * 180/math.pi

90.62270722408209

In [50]:
math.acos(np.dot(spoon, food)/(np.linalg.norm(spoon)* np.linalg.norm(food))) * 180/math.pi

90.48953209153744

In [51]:
math.acos(np.dot(spoon, tennis)/(np.linalg.norm(spoon)* np.linalg.norm(tennis))) * 180/math.pi

91.51636275815346

In [52]:
math.acos(np.dot(player, food)/(np.linalg.norm(player)* np.linalg.norm(food))) * 180/math.pi

90.07699157279768

In [53]:
math.acos(np.dot(player, tennis)/(np.linalg.norm(player)* np.linalg.norm(tennis))) * 180/math.pi

90.60762086020966

In [56]:
np.save('wn_words.npz', wn_unique_words)

In [55]:
wn_dict_copy["jewel"]

5